name: Run on schedule
on:
  schedule:
    # 장 마감(15:30 서울) 후 10분 뒤 실행
    # 15:40 KST = 06:40 UTC
    # 40 : 10분
    # 6 : 오전 6시 (UTC 기준)
    # * * : 매일 매월
    # 1-5 : 월~금 (0: 일요일, 6: 토요일)
    # - cron: "40 6 * * 1-5"
    - cron: "40 15 * * 1-5"
      timezone: "Asia/Seoul"
    - cron: "0 17 * * 1-5"
      timezone: "Asia/Seoul"
  # 2. 수동 실행 허용
  workflow_dispatch:
jobs:
  run-judal-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # 원하는 버전 입력
          cache: "pip" # 위에서 배운 캐싱도 한 줄로 추가!

      - name: 패키지 설치
        run: pip install -r requirements.txt

      - name: 코드 실행
        run: |
          mkdir tmp
          python judal.py

      - name: 오늘 날짜 확인
        id: check_date
        run: |
          # 1. 파일에서 날짜 읽기
          DAY_STR=$(cat ./DAY | xargs)
          # 2. 시스템의 오늘 날짜 가져오기 (YYYY-MM-DD 형식)
          # 한국 시간(KST) 기준이라면 TZ 설정을 추가하세요.
          TODAY=$(TZ='Asia/Seoul' date +'%Y-%m-%d')

          echo "파일 날짜: $DAY_STR"
          echo "오늘 날짜: $TODAY"

          # 3. 비교 결과 저장
          if [ "$DAY_STR" == "$TODAY" ]; then
            echo "match=true" >> $GITHUB_OUTPUT
          else
            echo "match=false" >> $GITHUB_OUTPUT
          fi

      - name: Gist 업로드
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: "ab2e3c2825bd77e772a5bae939bae5f5" # 생성해 둔 Gist ID 입력
        run: |
          # 1. DAY 파일에서 날짜 읽기
          DAY_STR=$(cat ./DAY)
          FILENAME="stock_interest_${DAY_STR}.md"
          # 2. 파일 존재 확인 (디버깅용)
          if [ ! -f "$FILENAME" ]; then
            echo "에러: $FILENAME 파일을 찾을 수 없습니다."
            exit 1
          fi
          # 3. GitHub CLI를 사용하여 Gist 업데이트
          # -f 옵션은 해당 이름의 파일이 Gist에 있으면 덮어쓰고, 없으면 추가합니다.
          #gh gist edit $GIST_ID -f "$FILENAME"="$FILENAME"
          gh gist edit $GIST_ID --add "$FILENAME"

      - name: DB 파일 보관하기
        if: steps.check_date.outputs.match == 'true' # 날짜가 일치할 때만 실행
        uses: actions/upload-artifact@v4
        with:
          name: stock-database # Artifact의 이름
          path: stock_data.db3 # 보관할 파일 경로
          retention-days: 30 # 보관 기간 (기본 90일, 최대 90일)
